### PR TITLE
Feature/187838825 - Game Demo Page - Setup

### PR DESCRIPTION
**Pull request by jeremymccurdy-redspace**
Adding the game demo to an examples page. Ported over from the original demo page.

Has a basic Container setup, to be expanded upon in future PRs. This includes all of the buttons that were in the original demo page, I'll remove any unnecessary ones after implementing the rest of the demo page.

Ticket: https://www.pivotaltracker.com/story/show/187838825

### CODE REVIEW

**Review by 902seanryan — APPROVED** [review]
Setup looks good to me, we could also have the examples as their own page rather than another section in the docs if it made more sense? 
Don't have to make the call now, because the way you wrote it will make it real easy to switch later, just curious what your thoughts are on the organization

**Comment by jeremymccurdy-redspace** [comment]
> Setup looks good to me, we could also have the examples as their own page rather than another section in the docs if it made more sense? Don't have to make the call now, because the way you wrote it will make it real easy to switch later, just curious what your thoughts are on the organization

Yeah I was wondering where it should actually live. The game demo is technically a demo for both SpringRoll and Container now. It probably makes sense to have it's own page. 

I'll do that now. I just noticed that I didn't support dark mode with the button and header colors, so I'm already going to be in and fixing stuff anyway.

**Review by corinnejean — APPROVED** [review]

**Comment by corinnejean** [comment]
ooh I just saw your comment @jeremymccurdy-redspace just re-request my review when you are ready!

**Comment by jeremymccurdy-redspace** [comment]
Updated the PR with Examples moved to its own section. I added a placeholder Introduction landing page for it. The buttons are now using styles from the theme and adapt to dark mode correctly.  

It took a while to sort out what they were using for styles, but it looks like most are coming from this design system: https://infima.dev/

**Review by selenaqian — APPROVED** [review]

**Comment by 902seanryan** [comment]
> Updated the PR with Examples moved to its own section. I added a placeholder Introduction landing page for it. The buttons are now using styles from the theme and adapt to dark mode correctly.
> 
> It took a while to sort out what they were using for styles, but it looks like most are coming from this design system: https://infima.dev/

yeah the Infima docs are woefully incomplete as well, but its baked into the framework. If you ever need to overwrite anything its all variable based but you'll have to scan the code itself, or use the inspector unfortunately

**Review by 902seanryan — APPROVED** [review]

**Comment by 902seanryan** [comment]
@jeremymccurdy-redspace sorry, just noticed that the captions text doesn't change with dark mode so its not really visible. I imagine they're part of the game so do you think it'd be reasonable to just move them up so they're on the iframe background or maybe just add a white background? 

Doesn't have to be done now just noting it

**Comment by jeremymccurdy-redspace** [comment]
> @jeremymccurdy-redspace sorry, just noticed that the captions text doesn't change with dark mode so its not really visible. I imagine they're part of the game so do you think it'd be reasonable to just move them up so they're on the iframe background or maybe just add a white background?
> 
> Doesn't have to be done now just noting it

Yeah I meant to call out in the channel that we should do a general update of the demo game. The captions setup is an issue, it also doesn't implement screen scaling, and it's using a really old version of SpringRoll (from 2018).

I think an update should be it's own task in this case.

**Comment by jeremymccurdy-redspace** [comment]
@902seanryan I think I can change the iframe background though, so I will give that a shot.

**Review by 902seanryan — APPROVED** [review]

**Pull request merged**
